<?php
/**
 * Blog post list template
 *
 * @var $block \TCK\Blog\Block\PostList
 */

$helper = $this->getHelper();
?>
<div class="entry-content">
<?php foreach ($block->getPosts() as $_post): ?>
  <article id="post-<?php echo $_post->getId(); ?>">
    <header>
      <p class="date"><?php echo $helper->parseDate($_post->getCreationTime()); ?></p>
      <h2><a href="<?php echo $_post->getUrl() ?>"><?php echo $_post->getTitle() ?></a></h2>
    </header>
    <div class="post-summary">
      <?php echo $_post->getSummary(); ?>
    </div>
  </article>
<?php endforeach; ?>
</div>
