<?php
/**
 * Blog post view template
 *
 * @var $block \TCK\Blog\Block\PostView
 */

$_post = $this->getPost();
$helper = $this->getHelper();
$date = $helper->parseDate($_post->getCreationTime());
?>
<div class="entry-content">
  <article id="post-<?php echo $_post->getId(); ?>">
  <div class="article-top">
  <?php if ($_post->isShareableFacebook()) : ?>
    <a class="icon-share" href="#" title="<?php echo __('Share in') ?> Facebook"><img alt="Facebook" src="<?php echo $this->getViewFileUrl('TCK_Blog::images/facebook.png')?>" width="32" /></a>
  <?php
    endif;
    if ($_post->isShareableTwitter()) :
  ?>
    <a class="icon-share" href="#" title="<?php echo __('Share in') ?> Twitter"><img alt="Twitter" src="<?php echo $this->getViewFileUrl('TCK_Blog::images/twitter.png')?>" width="32" /></a>
  <?php
    endif;
    if ($_post->isShareableGoogleplus()) :
  ?>
    <a class="icon-share" href="#" title="<?php echo __('Share in') ?> Google+"><img alt="Google+" src="<?php echo $this->getViewFileUrl('TCK_Blog::images/google-plus1.png')?>" width="32" /></a>
  <?php endif; ?>
    <p class="date"><?php echo $date ?></p>
  </div>
  <?php echo $_post->getContent(); ?>
  </article>
  <p><a href="../" title="<?php echo __('Back to index') ?>"><?php echo __('Back') ?></a></p>
</div>
