<?php
/**
 * Blog post view template
 *
 * @var $block \TCK\Blog\Block\PostView
 */

$_post = $this->getPost();
$helper = $this->getHelper();
$date = $helper->parseDate($_post->getCreationTime());
?>
<div class="entry-content">
  <p class="date"><?php echo $date ?></p>
  <?php echo $_post->getContent(); ?>
  <hr class="tall">
  <?php if ($_post->isShareable()) : ?>
  <h3><?php echo __('Share') ?></h3>
  <p>
    <?php if ($_post->isShareableFacebook()) : ?>
      <a href="#" title="<?php echo __('Share in') ?> Facebook"><img alt="Facebook" src="<?php echo $this->getViewFileUrl('TCK_Blog::images/facebook.png')?>" width="64" /></a>
    <?php
      endif;
      if ($_post->isShareableTwitter()) :
    ?>
      <a href="#" title="<?php echo __('Share in') ?> Twitter"><img alt="Twitter" src="<?php echo $this->getViewFileUrl('TCK_Blog::images/twitter.png')?>" width="64" /></a>
      <?php
        endif;
        if ($_post->isShareableGoogleplus()) :
      ?>
      <a href="#" title="<?php echo __('Share in') ?> Google+"><img alt="Google+" src="<?php echo $this->getViewFileUrl('TCK_Blog::images/google-plus1.png')?>" width="64" /></a>
    <?php endif; ?>
  </p>
  <?php endif; ?>
  <p><a href="../" title="<?php echo __('Back to index') ?>"><?php echo __('Back') ?></a></p>
</div>
